services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    container_name: dbarchperf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/data/dbarchperf:/var/lib/postgresql/data
    networks:
      dbarchperf:
        ipv4_address: 172.16.15.2
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    container_name: dbarchperf-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      dbarchperf:
        ipv4_address: 172.16.15.3

networks:
  dbarchperf:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.15.0/28
